
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yonshisoru
 */
public class Customer_Claim_View extends javax.swing.JFrame {
Database d = new Database();
Connection con = null;
PreparedStatement pat = null;
ResultSet rs = null;
ArrayList<Menu_variable> Menu_Array = new ArrayList<>();
ArrayList<Menu_variable> Ordering_List_Array = new ArrayList<>();
ArrayList<Customer_variable>Report_Array= new ArrayList<>();
    /**
     * Creates new form Customer_Claim_View
     */
    public Customer_Claim_View() {
        initComponents();
        getMenu();
        getReport();
        getorder_menu();
        setReport();
    }
 public Connection getcon(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            return DriverManager.getConnection(d.url(),d.username(),d.password());
        }catch(Exception e){
            System.out.println(e.getMessage());
            System.out.println("Didn't connect");
            throw new RuntimeException(e);
        }
    }
    public void getMenu(){
        String sql = "Select MENU_ID,MENU_NAME,MENU_PRICE,M_T_ID FROM MENU WHERE MENU_DEL = 'N'";
        try{
            pat = getcon().prepareStatement(sql);
            rs = pat.executeQuery(sql);
            while(rs.next()){
                Menu_variable m = new Menu_variable();
                m.setid(rs.getString("MENU_ID"));
                m.setname(rs.getString("MENU_NAME"));
                m.setprice(rs.getInt("MENU_PRICE"));
                m.setcataid(rs.getString("M_T_ID"));
                Menu_Array.add(m);
            }
            rs.close();
            pat.close();
            getcon().close();
        }catch(Exception e){

        }
    }
   public void getReport(){
        String sql = "Select REP_NUMBER,OM_ID,REP_DATE,REP_DETAIL FROM REP_ORDER WHERE REP_DEL = 'N'";
        try{
            pat = getcon().prepareStatement(sql);
            rs = pat.executeQuery(sql);
            while(rs.next()){
                Customer_variable c = new Customer_variable();
                c.setreportid(rs.getString("REP_NUMBER"));
                c.setorder_menu_id(rs.getString("OM_ID"));
                c.setdate(rs.getString("REP_DATE"));
                c.setdetail(rs.getString("REP_DETAIL"));
                Report_Array.add(c);
            }
            rs.close();
            pat.close();
            getcon().close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    public void getorder_menu(){
        String sql = "Select OM_ID,ORD_ID,MENU_ID,OM_UNITS,OM_PRICE,OM_STATUS FROM ORDER_MENU_LIST";
        //System.out.println(sql);
        try{
            pat = getcon().prepareStatement(sql);
            rs = pat.executeQuery(sql);
            while(rs.next()){
                Menu_variable m = new Menu_variable();
                m.c.setorder_menu_id(rs.getString("OM_ID"));
                m.c.setorderid(rs.getString("ORD_ID"));
                m.setid(rs.getString("MENU_ID"));
                for(Menu_variable mv :Menu_Array){
                    if(m.getid().equals(mv.getid())){
                        m.setname(mv.getname());
                        break;
                    }
                }
                m.c.setunits(rs.getInt("OM_UNITS"));
                m.c.settotal(rs.getDouble("OM_PRICE"));
                m.c.setorder_menu_status(rs.getString("OM_STATUS"));
                Ordering_List_Array.add(m);
            }
            rs.close();
            pat.close();
            getcon().close();
        }catch(Exception e){

        }
    }
   public void setReport(){
       DefaultTableModel model = (DefaultTableModel)report_table.getModel();
       Object[] row = new Object[6];
       for(Customer_variable c:Report_Array){
           row[0] = c.getreportid();
           row[1] = c.getorder_menu_id();
           for(Menu_variable m:Ordering_List_Array){
               if(m.c.getorder_menu_id().equals(c.getorder_menu_id())){
                   for(Menu_variable mm:Menu_Array){
                       if(m.getid().equals(mm.getid())){
                                      row[2] = mm.getname();
                       }
                   }
               }
                          row[3] = m.c.gettotal();
                          break;
           }
           row[4] = c.getdate();
           row[5] = c.getdetail();
           model.addRow(row);
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        report_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1050, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        report_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รายการที่", "รหัสออเดอร์ที่", "ชื่อเมนู", "ราคา", "วันที่", "รายละเอียด"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(report_table);
        if (report_table.getColumnModel().getColumnCount() > 0) {
            report_table.getColumnModel().getColumn(0).setResizable(false);
            report_table.getColumnModel().getColumn(0).setPreferredWidth(70);
            report_table.getColumnModel().getColumn(1).setResizable(false);
            report_table.getColumnModel().getColumn(1).setPreferredWidth(120);
            report_table.getColumnModel().getColumn(2).setResizable(false);
            report_table.getColumnModel().getColumn(2).setPreferredWidth(200);
            report_table.getColumnModel().getColumn(3).setResizable(false);
            report_table.getColumnModel().getColumn(4).setResizable(false);
            report_table.getColumnModel().getColumn(4).setPreferredWidth(200);
            report_table.getColumnModel().getColumn(5).setResizable(false);
            report_table.getColumnModel().getColumn(5).setPreferredWidth(500);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 890, 380));

        jButton1.setText("ปิด");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Claim_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Claim_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Claim_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Claim_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Claim_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable report_table;
    // End of variables declaration//GEN-END:variables
}
