
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yonshisoru
 */
public class Customer_History extends javax.swing.JFrame {
Database d = new Database();
Table_variable t = new Table_variable();

Connection con = null;
PreparedStatement pat = null;
ResultSet rs = null;
ArrayList<Menu_variable> Ordering_Array = new ArrayList<>();  

String year = LocalDate.now().toString().substring(0,4);

double total = 0;
    /**
     * Creates new form Customer_History
     */
    public Customer_History() {
        initComponents();
    }
    public Connection getcon(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            return DriverManager.getConnection(d.url(),d.username(),d.password());
        }catch(Exception e){
            System.out.println(e.getMessage());
            System.out.println("Didn't connect");
            throw new RuntimeException(e);
        }
    }
public void getorder(String year,String month,String date){
        String sql = "Select ORD_ID,EMP_ID,T_ID,ORD_DATE,ORD_TOTAL,ORD_PAYTYPE FROM ORDERING WHERE ORD_DEL = 'N' AND ORD_DATE>='"+year+"-"+month+"-01' AND ORD_DATE<='"+year+"-"+month+"-"+date+"'";
        System.out.println(sql);
        try{
            pat = getcon().prepareStatement(sql);
            rs = pat.executeQuery(sql);
            while(rs.next()){
                Menu_variable m = new Menu_variable();
                m.c.setorderid(rs.getString("ORD_ID"));
                m.e.setid(rs.getString("EMP_ID"));
                m.c.settable(rs.getString("T_ID"));
                m.c.setorderdate(rs.getString("ORD_DATE"));
                m.c.settotal(rs.getDouble("ORD_TOTAL"));
                m.c.setpaytype(rs.getString("ORD_PAYTYPE"));
                Ordering_Array.add(m);
            }
            rs.close();
            pat.close();
            getcon().close();
        }catch(Exception e){
            
        }
    }
public void setorder(){
    DefaultTableModel model = (DefaultTableModel)order_table.getModel();
    Object[] row = new Object[4];
    for(Menu_variable m:Ordering_Array){
        row[0] = m.c.getorderid();
        row[1] = m.c.getorderdate();
        row[2] = m.c.gettotal();
        row[3] = m.c.getpaytype();
        total += m.c.gettotal();
        model.addRow(row);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        order_table = new javax.swing.JTable();
        month_combo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        total_txt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        order_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รหัสออเดอร์", "วันที่", "ราคา", "ประเภทการจ่าย"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(order_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 650, -1));

        month_combo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        month_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "เลือกเดือน", "มกราคม", "กุมภาพันธ์", "มีนาคม", "เมษายน", "พฤษภาคม", "มิถุนายน", "กรกฎาคม", "สิงหาคม", "กันยายน", "ตุลาคม", "พฤศจิกายน", "ธันวาคม" }));
        month_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month_comboActionPerformed(evt);
            }
        });
        getContentPane().add(month_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("เดือน");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("จำนวนออเดอร์ทั้งหมด:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("รายการ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("0");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 130, 20));

        total_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_txt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        total_txt.setText("0.00");
        getContentPane().add(total_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("ยอดขายสุทธิ:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("บาท");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, -1, -1));

        jButton1.setText("ปิด");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 140, 60));

        jButton2.setText("พิมพ์เป็น PDF ");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, 140, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void month_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month_comboActionPerformed
        total=0;
        if(month_combo.getSelectedIndex()==0){
            DefaultTableModel model = (DefaultTableModel)order_table.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            Ordering_Array.clear(); 
        }else if(month_combo.getSelectedIndex()==1){
            DefaultTableModel model = (DefaultTableModel)order_table.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            Ordering_Array.clear();
            getorder(year,"01","31");
            setorder();
        }else if(month_combo.getSelectedIndex()==2){
            DefaultTableModel model = (DefaultTableModel)order_table.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            Ordering_Array.clear();
            getorder(year,"02","28");
            setorder(); 
        }else if(month_combo.getSelectedIndex()==3){
            DefaultTableModel model = (DefaultTableModel)order_table.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            Ordering_Array.clear();
            getorder(year,"03","31");
            setorder();
        }else if(month_combo.getSelectedIndex()==4){
            DefaultTableModel model = (DefaultTableModel)order_table.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            Ordering_Array.clear();
            getorder(year,"04","30");
            setorder();
        }else if(month_combo.getSelectedIndex()==5){
            DefaultTableModel model = (DefaultTableModel)order_table.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            Ordering_Array.clear();
            getorder(year,"05","31");
            setorder();
        }else if(month_combo.getSelectedIndex()==6){
            DefaultTableModel model = (DefaultTableModel)order_table.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            Ordering_Array.clear();
            getorder(year,"06","30");
            setorder();
        }else if(month_combo.getSelectedIndex()==7){
            DefaultTableModel model = (DefaultTableModel)order_table.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            Ordering_Array.clear();
            getorder(year,"07","31");
            setorder();
        }else if(month_combo.getSelectedIndex()==8){
            DefaultTableModel model = (DefaultTableModel)order_table.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            Ordering_Array.clear();
            getorder(year,"08","31");
            setorder();
        }else if(month_combo.getSelectedIndex()==9){
            DefaultTableModel model = (DefaultTableModel)order_table.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            Ordering_Array.clear();
            getorder(year,"09","30");
            setorder();
        }else if(month_combo.getSelectedIndex()==10){
            DefaultTableModel model = (DefaultTableModel)order_table.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            Ordering_Array.clear();
            getorder(year,"10","31");
            setorder();
        }else if(month_combo.getSelectedIndex()==11){
            
            DefaultTableModel model = (DefaultTableModel)order_table.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            Ordering_Array.clear();
            getorder(year,"11","30");
            setorder();
        }else if(month_combo.getSelectedIndex()==12){
            DefaultTableModel model = (DefaultTableModel)order_table.getModel();
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            Ordering_Array.clear();
            getorder(year,"12","31");
            setorder();
        }
        total_txt.setText(String.format("%.2f",total));
    }//GEN-LAST:event_month_comboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> month_combo;
    private javax.swing.JTable order_table;
    private javax.swing.JLabel total_txt;
    // End of variables declaration//GEN-END:variables
}
