/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yonshisoru
 */
public class Employee_Table extends javax.swing.JFrame {
    Database d = new Database();
    Employee e = new Employee();
    Main_variable m = new Main_variable();
    public String id = null;
    Connection con = null;
    Statement pat = null;
    ResultSet rs = null;
    int count = 0;
    static public String usingid = null;
    String old = null;
    ArrayList<Employee> EmployeeList = new ArrayList<>();
    /**
     * Creates new form Employee_Table
     */
    public Employee_Table() {
        initComponents();
        show_employee();
        if(m.getleave()==1){
            jLabel1.setText("Employee Leave List");
        }
        if(m.editenable()==1){
            jLabel1.setText("Editing Schedule");
        }
    }
    public ArrayList<Employee>EmployeeList(){
        try{
        Class.forName("com.mysql.jdbc.Driver");
        String sql  ="select EMP_ID,EMP_FNAME,EMP_LNAME,POS_NAME,EMP_AGE,EMP_GENDER,EMP_START,EMP_PHONE,EMP_EMAIL from EMPLOYEE NATURAL JOIN EMP_POSITION WHERE EMP_DEL = 'N' ORDER BY EMP_ID";         
        /*con = DriverManager.getConnection("jdbc:mysql://localhost:3306/u787124245_dulce","root","");*/
        con = DriverManager.getConnection(d.url(),d.username(),d.password());
        pat = con.createStatement();
        rs = pat.executeQuery(sql);
        while(rs.next()){
            Employee e = new Employee(rs.getString("EMP_ID"),rs.getString("EMP_FNAME"),rs.getString("EMP_LNAME"),rs.getString("POS_NAME"),rs.getInt("EMP_AGE"),rs.getString("EMP_GENDER"),rs.getString("EMP_PHONE"),rs.getString("EMP_EMAIL"),rs.getString("EMP_START"));
            EmployeeList.add(e);
        }
        con.close();
        pat.close();
        rs.close();
        }catch(Exception e){
            e.printStackTrace();
        }
        return EmployeeList;
}
    public void show_employee(){
        DefaultTableModel model = (DefaultTableModel)emp_table.getModel();
        EmployeeList = EmployeeList();
        Object[] row = new Object[9];
        for(int i=0;i<EmployeeList.size();i++){
            row[0]=EmployeeList.get(i).getid();
            row[1]=EmployeeList.get(i).getposition();
            row[2]=EmployeeList.get(i).getfname();
            row[3]=EmployeeList.get(i).getlname();
            row[4]=EmployeeList.get(i).getage();
            row[5]=EmployeeList.get(i).getgender();
            row[6]=EmployeeList.get(i).getphone();
            row[7]=EmployeeList.get(i).getemail();
            row[8]=EmployeeList.get(i).getdate();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        emp_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 550));
        setPreferredSize(new java.awt.Dimension(800, 570));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emp_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รหัสพนักงาน", "ตำแหน่ง", "ชื่อ", "นามสกุล", "อายุ", "เพศ", "เบอร์โทรศัพท์", "อีเมลล์", "วันเริ่มทำงาน"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        emp_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emp_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(emp_table);
        if (emp_table.getColumnModel().getColumnCount() > 0) {
            emp_table.getColumnModel().getColumn(4).setMinWidth(30);
            emp_table.getColumnModel().getColumn(4).setMaxWidth(40);
            emp_table.getColumnModel().getColumn(5).setMinWidth(50);
            emp_table.getColumnModel().getColumn(5).setMaxWidth(60);
            emp_table.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 860, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ตารางพนักงาน");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 10, 830, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        jButton1.setText("ปิด");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Main_variable mk = new Main_variable();
        mk.setleavenaja(false);
        mk.setleave(0);
        mk.setchange(false);
        mk.seteditenable(0);
    }//GEN-LAST:event_formWindowClosing

    private void emp_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_tableMouseClicked
        if(m.editenable()==1&&m.geton()==0){
        if(emp_table.getModel().getValueAt(emp_table.getSelectedRow(),0).toString().equals(old)&&count==1){
           count=0;
            if(emp_table.getModel().getValueAt(emp_table.getSelectedRow(),0).toString().equals(e.getshowid())){
                JOptionPane.showMessageDialog(null, "That's you!!\n You can't do that.", "System", ERROR_MESSAGE);
            }else{
            m.setid(emp_table.getModel().getValueAt(emp_table.getSelectedRow(),0).toString());
            m.setname(emp_table.getModel().getValueAt(emp_table.getSelectedRow(),2).toString()+" "+emp_table.getModel().getValueAt(emp_table.getSelectedRow(),3).toString());
            System.out.print(m.getid());
            m.seton(1);
            Schedule_Edit_admin sc = new Schedule_Edit_admin();
            sc.setVisible(true);
            count = 0;
            }
        }else{
            old = emp_table.getModel().getValueAt(emp_table.getSelectedRow(),0).toString();
            count=1;
        };
        }else if(m.getleave()==1&&m.geton()==0){
           if(emp_table.getModel().getValueAt(emp_table.getSelectedRow(),0).toString().equals(old)&&count==1){
            /*if(emp_table.getModel().getValueAt(emp_table.getSelectedRow(),0).toString().equals(e.getshowid())){
                JOptionPane.showMessageDialog(null, "That's you!!\n You can't do that.", "System", ERROR_MESSAGE);
            }else{*/
            m.setid(emp_table.getModel().getValueAt(emp_table.getSelectedRow(),0).toString());
            m.setname(emp_table.getModel().getValueAt(emp_table.getSelectedRow(),2).toString()+" "+emp_table.getModel().getValueAt(emp_table.getSelectedRow(),3).toString());
            System.out.print(m.getid());
            m.seton(1);
            Schedule_show_leave sc = new Schedule_show_leave();
            sc.setVisible(true);
            count=0;
            }else{
            old = emp_table.getModel().getValueAt(emp_table.getSelectedRow(),0).toString();
            count=1;
        }
        /*}*/
        }
    /*if(mk.editenable()==1){  */  
        /*}/*
        if(count==2){
            usingid = emp_table.getModel().getValueAt(emp_table.getSelectedRow(),0).toString();
        System.out.print(emp_table.getModel().getValueAt(emp_table.getSelectedRow(),0).toString());
        s.setVisible(true);
        count=0;
        }*/
    }//GEN-LAST:event_emp_tableMouseClicked

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated

    }//GEN-LAST:event_formWindowDeactivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable emp_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
