/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Yonshisoru
 */
public class Main extends javax.swing.JFrame{
Main_variable m = new Main_variable();
    Connection con = null;
    PreparedStatement pat = null;
    ResultSet rs = null;
    Database d = new Database();
    ArrayList<Employee> em = new ArrayList<Employee>();
    int max = 0;
    String output = null;
    String start = null;
    String end = null;
    String year = null;
    String month = null;
    String day = null;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Menu_Ordering.setVisible(false);
        Schedule.setVisible(false);
        Management_panel.setVisible(false);
        Inventory_panel.setVisible(false);
        Employee_panel.setVisible(false);
        Employee.setVisible(false);
        Inventory_btn.setVisible(false);
        Management_btn.setVisible(false);
        Employee e = new Employee();
        showname.setText(e.getdisfname()+" "+e.getdislname());
        showTime();
        showtime();
        System.out.print(e.gettype_id());
        if(e.gettype_id()==0||e.gettype_id()==1){
            Inventory_btn.setVisible(true);
            Management_btn.setVisible(true);
        }else{
        }
    }
    void showTime(){
        new Timer(0,new ActionListener(){
            
            @Override
            public void actionPerformed(ActionEvent e){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MMM-YYYY HH:mm:ss");
        Showtime.setText(s.format(d));
            }
        }).start();
    }
        void showtime(){
         Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("YYYY-MM-dd");
        year = String.valueOf(Integer.parseInt(s.format(d).substring(0,4))-543);
        month = String.valueOf(Integer.parseInt(s.format(d).substring(5,7)));
        day = String.valueOf(Integer.parseInt(s.format(d).substring(s.format(d).length()-2,s.format(d).length())));
        start = "'"+year+"-01-01'";
        end = "'"+year+"-12-31'";
        System.out.print(year+month+day);
    }
   public String id(){
       int count=0;
          String sql  ="select SP_ID from SALARY_PAYMENT";
    try{
    Class.forName("com.mysql.jdbc.Driver");
    con = DriverManager.getConnection(d.url(),d.username(),d.password());
    pat = con.prepareStatement(sql);
     rs = pat.executeQuery(sql);
    while(rs.next()){
        count++;
        if(Integer.parseInt(rs.getString("SP_ID").substring(1,4))>max){
            max = Integer.parseInt(rs.getString("SP_ID").substring(1,4));
        }
    }
    if(count==0){
            max = 0;
    }
    max += 1;
    if(max<10){
        output = "S00"+max;
    }else if(max<100){
        output = "S0"+max;
    }else{
        output = "S"+max;
    }
    System.out.print(output);
    con.close();
    pat.close();
    rs.close();
            }catch(Exception e){
                e.printStackTrace();
            }
    return output;
   } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        Showtime = new javax.swing.JLabel();
        Showdate = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        Time1 = new javax.swing.JLabel();
        showname = new javax.swing.JLabel();
        ButtonPanel = new javax.swing.JPanel();
        Menu_Ordering_btn = new javax.swing.JButton();
        Schedule_btn = new javax.swing.JButton();
        Inventory_btn = new javax.swing.JButton();
        Management_btn = new javax.swing.JButton();
        Employee_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Selection = new javax.swing.JPanel();
        Firstpage = new javax.swing.JPanel();
        Menu_Ordering = new javax.swing.JPanel();
        Heading_MO = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        ordering_management = new javax.swing.JButton();
        Schedule = new javax.swing.JPanel();
        Heading_Sc = new javax.swing.JLabel();
        leave = new javax.swing.JButton();
        preenrolled = new javax.swing.JButton();
        editenrolled = new javax.swing.JButton();
        CreateSchedule = new javax.swing.JButton();
        ShowSchedule = new javax.swing.JButton();
        Change_schedule = new javax.swing.JButton();
        Leave_list = new javax.swing.JButton();
        view_leave = new javax.swing.JButton();
        Management_panel = new javax.swing.JPanel();
        Heading_OP = new javax.swing.JLabel();
        product_panel = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        Employee_Management_btn = new javax.swing.JButton();
        Employee_salary_btn = new javax.swing.JButton();
        Employee_Payment_btn = new javax.swing.JButton();
        Employee_Clockin_out_btn = new javax.swing.JButton();
        Set_Period_Payment_btn = new javax.swing.JButton();
        View_Employee_Payment_btn = new javax.swing.JButton();
        Inventory_panel = new javax.swing.JPanel();
        Heading_INV = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        Ordering_product1 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        Employee_panel = new javax.swing.JPanel();
        Heading_INV1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Employee = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Employee_salary = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Employee_Payment_btn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1070, 730));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopPanel.setOpaque(false);
        TopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name.setText("Name:");
        TopPanel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        Showtime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Showtime.setText("24/11/2561 16.30");
        TopPanel.add(Showtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 210, 20));
        TopPanel.add(Showdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 130, 20));

        jButton16.setText("Logout");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        TopPanel.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        Time1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Time1.setText("Time:");
        TopPanel.add(Time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        showname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        showname.setText("Dulce Simply");
        TopPanel.add(showname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 260, -1));

        getContentPane().add(TopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1040, 40));

        ButtonPanel.setOpaque(false);
        ButtonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu_Ordering_btn.setText("Menu Ordering");
        Menu_Ordering_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Ordering_btnActionPerformed(evt);
            }
        });
        ButtonPanel.add(Menu_Ordering_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 143, 50));

        Schedule_btn.setText("Schedule");
        Schedule_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Schedule_btnActionPerformed(evt);
            }
        });
        ButtonPanel.add(Schedule_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, 143, 50));

        Inventory_btn.setText("Inventory");
        Inventory_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inventory_btnActionPerformed(evt);
            }
        });
        ButtonPanel.add(Inventory_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, 143, 51));

        Management_btn.setText("Management");
        Management_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Management_btnActionPerformed(evt);
            }
        });
        ButtonPanel.add(Management_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 331, 143, 51));

        Employee_btn.setText("Employee");
        Employee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_btnActionPerformed(evt);
            }
        });
        ButtonPanel.add(Employee_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 143, 55));

        jButton1.setText("ปิดยอดขาย");
        ButtonPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 160, 60));

        getContentPane().add(ButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, 678));

        Selection.setBackground(new java.awt.Color(254, 255, 239));
        Selection.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Selection.setPreferredSize(new java.awt.Dimension(800, 500));

        Firstpage.setBackground(new java.awt.Color(254, 255, 239));
        Firstpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu_Ordering.setBackground(new java.awt.Color(254, 255, 239));
        Menu_Ordering.setPreferredSize(new java.awt.Dimension(1000, 700));
        Menu_Ordering.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading_MO.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Heading_MO.setText("การออร์เดอร์");
        Menu_Ordering.add(Heading_MO, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        jButton2.setText("Menu Ordering");
        Menu_Ordering.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 160, 90));

        jButton11.setText("Table");
        Menu_Ordering.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 180, 90));

        jButton12.setText("Promotion");
        Menu_Ordering.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 170, 90));

        jButton3.setText("Payment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Menu_Ordering.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 180, 90));

        jButton13.setText("Report");
        Menu_Ordering.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 170, 100));

        jButton14.setText("History");
        Menu_Ordering.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 160, 90));

        ordering_management.setText("Ordering management");
        Menu_Ordering.add(ordering_management, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 180, 90));

        Schedule.setBackground(new java.awt.Color(254, 255, 239));
        Schedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading_Sc.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Heading_Sc.setText("Schedule");
        Schedule.add(Heading_Sc, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 30, -1, -1));

        leave.setText("บันทึกการลางาน");
        leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveActionPerformed(evt);
            }
        });
        Schedule.add(leave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 150, 64));

        preenrolled.setText("ลงเวลาล่วงหน้า");
        preenrolled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preenrolledActionPerformed(evt);
            }
        });
        Schedule.add(preenrolled, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 140, 64));

        editenrolled.setText("แก้ไขการลงเวลา");
        editenrolled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editenrolledActionPerformed(evt);
            }
        });
        Schedule.add(editenrolled, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 150, 64));

        CreateSchedule.setText("สร้างเวลาการเข้างาน");
        CreateSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateScheduleActionPerformed(evt);
            }
        });
        Schedule.add(CreateSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 140, 60));

        ShowSchedule.setText("ตารางเวลา");
        ShowSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowScheduleActionPerformed(evt);
            }
        });
        Schedule.add(ShowSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 150, 70));

        Change_schedule.setText("<html><center>จัดการการลงเวลา<br>ของพนักงาน</center></br></html>");
        Change_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change_scheduleActionPerformed(evt);
            }
        });
        Schedule.add(Change_schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 150, 60));

        Leave_list.setText("รายการลาทั้งหมด");
        Leave_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Leave_listActionPerformed(evt);
            }
        });
        Schedule.add(Leave_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 150, 60));

        view_leave.setText("ดูการลา");
        view_leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_leaveActionPerformed(evt);
            }
        });
        Schedule.add(view_leave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 140, 60));

        Management_panel.setBackground(new java.awt.Color(254, 255, 239));
        Management_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading_OP.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Heading_OP.setText("Management");
        Management_panel.add(Heading_OP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        product_panel.setText("จัดการอุปกรณ์/วัตถุดิบ");
        product_panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_panelActionPerformed(evt);
            }
        });
        Management_panel.add(product_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 160, 60));

        jButton20.setText("บริษัทผู้จัดจำหน่าย");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        Management_panel.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 160, 60));

        Employee_Management_btn.setText("เมนูจัดการพนักงาน");
        Management_panel.add(Employee_Management_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 150, 60));

        Employee_salary_btn.setText("<html><center>เงินเดือนของพนักงาน<br>\nทั้งหมด</center></br></html>");
        Employee_salary_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_salary_btnActionPerformed(evt);
            }
        });
        Management_panel.add(Employee_salary_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 160, 60));

        Employee_Payment_btn.setText("จ่ายเงินพนักงาน");
        Employee_Payment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_Payment_btnActionPerformed(evt);
            }
        });
        Management_panel.add(Employee_Payment_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 150, 60));

        Employee_Clockin_out_btn.setText("<html><center>ดูเวลาเข้า/ออกงาน<br>ของพนักงาน</center></br></html>\n");
        Employee_Clockin_out_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_Clockin_out_btnActionPerformed(evt);
            }
        });
        Management_panel.add(Employee_Clockin_out_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 160, 60));

        Set_Period_Payment_btn.setText("จัดการช่วงเวลาจ่ายเงินเดือน");
        Set_Period_Payment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Set_Period_Payment_btnActionPerformed(evt);
            }
        });
        Management_panel.add(Set_Period_Payment_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 160, 60));

        View_Employee_Payment_btn.setText("ดูการจ่ายเงินพนักงาน");
        View_Employee_Payment_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_Employee_Payment_btnActionPerformed(evt);
            }
        });
        Management_panel.add(View_Employee_Payment_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 160, 60));

        Inventory_panel.setBackground(new java.awt.Color(254, 255, 239));
        Inventory_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading_INV.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Heading_INV.setText("Inventory");
        Inventory_panel.add(Heading_INV, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 20, -1, -1));

        jButton22.setText("อุปกรณ์และวัตถุดิบ");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        Inventory_panel.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, 70));

        jButton23.setText("ดูการสั่งอุปกรณ์และวัตถุดิบ");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        Inventory_panel.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 150, 60));

        jButton25.setText("การรับสินค้าจากการสั่ง");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        Inventory_panel.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 150, 60));

        jButton26.setText("จัดการของเสีย");
        Inventory_panel.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 150, 70));

        jButton28.setText("เมนู");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        Inventory_panel.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 150, 70));

        Ordering_product1.setText("การสั่งอุปกรณ์และวัตถุดิบ");
        Ordering_product1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ordering_product1ActionPerformed(evt);
            }
        });
        Inventory_panel.add(Ordering_product1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 150, 70));

        jButton32.setText("<html><center>การจ่ายเงินสั่งอุปกรณ์<br>และวัตถุดิบ</center></br></html>");
        jButton32.setActionCommand("");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        Inventory_panel.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 150, 60));

        jButton15.setText("การนำเข้าสินค้า");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        Inventory_panel.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 150, 60));

        jButton18.setText("<html><center>การเคลมอุปกรณ์<br>และวัตถุดิบ</center></br></html>");
        Inventory_panel.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 150, 60));

        jButton24.setText("จัดการสต๊อกสินค้า");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        Inventory_panel.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 150, 60));

        jButton19.setText("การรับสินค้าจากการเคลม");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        Inventory_panel.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 150, 60));

        Employee_panel.setBackground(new java.awt.Color(254, 255, 239));

        Heading_INV1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Heading_INV1.setText("Employee");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Position", "Given name", "Family name", "Age", "Gender", "Phone number", "Email", "Hired date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout Employee_panelLayout = new javax.swing.GroupLayout(Employee_panel);
        Employee_panel.setLayout(Employee_panelLayout);
        Employee_panelLayout.setHorizontalGroup(
            Employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Employee_panelLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(Heading_INV1)
                .addContainerGap(279, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        Employee_panelLayout.setVerticalGroup(
            Employee_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Employee_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Heading_INV1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        Employee.setBackground(new java.awt.Color(254, 255, 239));
        Employee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Employee Management");
        Employee.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, 60));

        jButton30.setText("Employee Management");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        Employee.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 150, 60));

        jButton31.setText("Setting period payment");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        Employee.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 150, 60));

        jButton5.setText("<html><center>Employee Clock-in & Clock-out</center></br></html>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Employee.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 160, 70));

        Employee_salary.setText("Employee Salary");
        Employee_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_salaryActionPerformed(evt);
            }
        });
        Employee.add(Employee_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 150, 60));

        jButton6.setText("View Payment");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Employee.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 150, 60));

        Employee_Payment_btn1.setText("Employee Payment");
        Employee_Payment_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_Payment_btn1ActionPerformed(evt);
            }
        });
        Employee.add(Employee_Payment_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 160, 60));

        javax.swing.GroupLayout SelectionLayout = new javax.swing.GroupLayout(Selection);
        Selection.setLayout(SelectionLayout);
        SelectionLayout.setHorizontalGroup(
            SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Menu_Ordering, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Schedule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Firstpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Management_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Inventory_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SelectionLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Employee_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Employee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SelectionLayout.setVerticalGroup(
            SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionLayout.createSequentialGroup()
                .addComponent(Menu_Ordering, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SelectionLayout.createSequentialGroup()
                    .addComponent(Schedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 206, Short.MAX_VALUE)))
            .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SelectionLayout.createSequentialGroup()
                    .addComponent(Firstpage, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SelectionLayout.createSequentialGroup()
                    .addComponent(Management_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SelectionLayout.createSequentialGroup()
                    .addComponent(Inventory_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SelectionLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(Employee_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(17, 17, 17)))
            .addGroup(SelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Employee, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
        );

        getContentPane().add(Selection, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 65, 830, 620));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-262, -30, 2220, 1240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_Ordering_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Ordering_btnActionPerformed
        Employee e = new Employee();
        Menu_Ordering.setVisible(true);
        Schedule.setVisible(false);
        Firstpage.setVisible(false);
        Management_panel.setVisible(false);
        Inventory_panel.setVisible(false);
        Employee_panel.setVisible(false);
         Employee.setVisible(false);  
         ordering_management.setVisible(false);
         if(e.gettype_id()==0||e.gettype_id()==1){
             ordering_management.setVisible(true);
         }
    }//GEN-LAST:event_Menu_Ordering_btnActionPerformed

    private void Schedule_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Schedule_btnActionPerformed
        Employee e = new Employee();
        Menu_Ordering.setVisible(false);
        Schedule.setVisible(true);
        Firstpage.setVisible(false);
        Management_panel.setVisible(false);
        Inventory_panel.setVisible(false);
        Employee_panel.setVisible(false);
        Employee.setVisible(false);
        if(e.gettype_id()==0||e.gettype_id()==1){
        CreateSchedule.setVisible(true);
        Change_schedule.setVisible(true);
        Leave_list.setVisible(true);
        }else{
            CreateSchedule.setVisible(false);
            Change_schedule.setVisible(false);
            Leave_list.setVisible(false);
    }    
    }//GEN-LAST:event_Schedule_btnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Management_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Management_btnActionPerformed
        Menu_Ordering.setVisible(false);
        Schedule.setVisible(false);
        Firstpage.setVisible(false);
        Management_panel.setVisible(true);
        Inventory_panel.setVisible(false);
        Employee_panel.setVisible(false);
        Employee.setVisible(false);
    }//GEN-LAST:event_Management_btnActionPerformed

    private void Inventory_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inventory_btnActionPerformed
        Menu_Ordering.setVisible(false);
        Schedule.setVisible(false);
        Firstpage.setVisible(false);
        Management_panel.setVisible(false);
        Inventory_panel.setVisible(true);
        Employee_panel.setVisible(false);
                Employee.setVisible(false);
    }//GEN-LAST:event_Inventory_btnActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        this.setVisible(false);
        Employee em =new Employee();
            em.setid("");
            em.setfname("");
            em.setlname("");
            em.setposition("");
        LoginFrom f = new LoginFrom();
        JOptionPane.showMessageDialog(null,"Logout Success");
        f.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void Employee_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_btnActionPerformed
        Employee e = new Employee();
        Menu_Ordering.setVisible(false);
        Schedule.setVisible(false);
        Firstpage.setVisible(false);
        Management_panel.setVisible(false);
        Inventory_panel.setVisible(false);
        Employee_panel.setVisible(false);
        if(e.gettype_id()==0||e.gettype_id()==1){
        Employee.setVisible(true);
        }else{
            Employee_Table k = new Employee_Table();
            k.setVisible(true);
    }    
    }//GEN-LAST:event_Employee_btnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
 if (JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to close without signout?", "Close Window?", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            LoginFrom l = new LoginFrom();
            l.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_formWindowClosing

    private void CreateScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateScheduleActionPerformed
        Schedule_CreateSchedule c = new Schedule_CreateSchedule();
        c.setVisible(true);
    }//GEN-LAST:event_CreateScheduleActionPerformed

    private void preenrolledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preenrolledActionPerformed
    Schedule_Enroll_timeshift e = new Schedule_Enroll_timeshift();
    e.setVisible(true);
    }//GEN-LAST:event_preenrolledActionPerformed

    private void editenrolledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editenrolledActionPerformed
    Schedule_Edit e = new Schedule_Edit();
    e.setVisible(true);
    }//GEN-LAST:event_editenrolledActionPerformed

    private void ShowScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowScheduleActionPerformed
        Schedule_show e = new Schedule_show();
    e.setVisible(true);
    }//GEN-LAST:event_ShowScheduleActionPerformed

    private void leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveActionPerformed
    Schedule_leave e  = new Schedule_leave();
    e.setVisible(true);
    }//GEN-LAST:event_leaveActionPerformed

    private void Change_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change_scheduleActionPerformed
    if(m.editenable()==0&&m.getleavenaja()==false){
    m.seteditenable(1);
    m.setchange(true);
    Employee_Table e = new Employee_Table();
    e.setVisible(true);
    System.out.print(m.editenable()+" "+m.getchange()+" "+m.getleave()+" "+m.getleavenaja());
        }else{
        JOptionPane.showMessageDialog(null, "You can't use editor function more than once!");
    }
    }//GEN-LAST:event_Change_scheduleActionPerformed

    private void Leave_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Leave_listActionPerformed
    if(m.getleave()==0&&m.getchange()==false){
    m.setleave(1);
    m.setleavenaja(true);
    Employee_Table e = new Employee_Table();
    e.setVisible(true);
    System.out.print(m.editenable()+" "+m.getchange()+" "+m.getleave()+" "+m.getleavenaja());
    }else{
        JOptionPane.showMessageDialog(null, "You can't use editor function more than once!");
    }
    }//GEN-LAST:event_Leave_listActionPerformed

    private void view_leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_leaveActionPerformed
    Schedule_show_emp_leave e  = new Schedule_show_emp_leave();
    e.setVisible(true);
    }//GEN-LAST:event_view_leaveActionPerformed

    private void Employee_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_salaryActionPerformed
    Employee_Salary e = new Employee_Salary();
    e.setVisible(true);
    }//GEN-LAST:event_Employee_salaryActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       Salary_payment s = new Salary_payment();
       s.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void product_panelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_panelActionPerformed
       Product_panel s = new Product_panel();
       s.setVisible(true);
    }//GEN-LAST:event_product_panelActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
       Vendor_panel s = new Vendor_panel();
       s.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void Ordering_product1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ordering_product1ActionPerformed
    Product_Order_panel p = new Product_Order_panel();
    p.setVisible(true);
    }//GEN-LAST:event_Ordering_product1ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
    m.setorderpayment(1);
    Product_Order_view p = new Product_Order_view();
    p.setVisible(true);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void Employee_salary_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_salary_btnActionPerformed
    Employee_Salary e = new Employee_Salary();
    e.setVisible(true);
    }//GEN-LAST:event_Employee_salary_btnActionPerformed

    private void Employee_Payment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_Payment_btnActionPerformed
Object[] possibilities = {"First Period", "Second Period"};
String s = (String)JOptionPane.showInputDialog(
                    null,
                    "What did period you want?"
                    ,
                    "System",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    possibilities,
                    "ham");

//If a string was returned, say so.
if ((s != null) && (s.length() > 0)) {
           String sql  ="select EMP_ID from EMPLOYEE WHERE EMP_DEL = 'N'";
        try{        
        /*con = DriverManager.getConnection("jdbc:mysql://localhost:3306/u787124245_dulce","root","");*/
        con = DriverManager.getConnection(d.url(),d.username(),d.password());
        pat = con.prepareStatement(sql);
        rs = pat.executeQuery();
        while(rs.next()){
            Employee n = new Employee();
            n.setid(rs.getString("EMP_ID"));
            em.add(n);
        }
        rs.close();
        pat.close();
        con.close();
        }catch(Exception e){
            
        }
    if(s.equals("First Period")){
        if(month.equals("01")){
        start = "'"+year+"-01-01'";
        end = "'"+year+"-01-15'"; 
        }else if(month.equals("02")){
        start = "'"+year+"-02-01'";
        end = "'"+year+"-02-15'";     
        }else if(month.equals("03")){
        start = "'"+year+"-03-01'";
        end = "'"+year+"-03-15'";    
        }else if(month.equals("04")){
        start = "'"+year+"-04-01'";
        end = "'"+year+"-04-15'";     
        }else if(month.equals("05")){
        start = "'"+year+"-05-01'";
        end = "'"+year+"-05-15'";     
        }else if(month.equals("06")){
         start = "'"+year+"-06-01'";
        end = "'"+year+"-06-15'";    
        }else if(month.equals("07")){
        start = "'"+year+"-07-01'";
        end = "'"+year+"-07-15'";     
        }else if(month.equals("08")){
         start = "'"+year+"-08-01'";
        end = "'"+year+"-08-15'";     
        }else if(month.equals("09")){
         start = "'"+year+"-09-01'";
        end = "'"+year+"-09-15'";    
        }else if(month.equals("10")){
         start = "'"+year+"-10-01'";
        end = "'"+year+"-10-15'";    
        }else if(month.equals("11")){
        start = "'"+year+"-11-01'";
        end = "'"+year+"-11-15'";     
        }else if(month.equals("12")){
        start = "'"+year+"-12-01'";
        end = "'"+year+"-12-15'";     
        }
    }else if(s.equals("Second Period")){ 
        if(month.equals("01")){
        start = "'"+year+"-01-15'";
        end = "'"+year+"-01-31'"; 
        }else if(month.equals("02")){
        start = "'"+year+"-02-15'";
        end = "'"+year+"-02-28'";     
        }else if(month.equals("03")){
        start = "'"+year+"-03-15'";
        end = "'"+year+"-03-31'";    
        }else if(month.equals("04")){
        start = "'"+year+"-04-15'";
        end = "'"+year+"-04-30'";     
        }else if(month.equals("05")){
        start = "'"+year+"-05-15'";
        end = "'"+year+"-05-31'";     
        }else if(month.equals("06")){
         start = "'"+year+"-06-15'";
        end = "'"+year+"-06-30'";    
        }else if(month.equals("07")){
        start = "'"+year+"-07-15'";
        end = "'"+year+"-07-31'";     
        }else if(month.equals("08")){
         start = "'"+year+"-08-15'";
        end = "'"+year+"-08-31'";     
        }else if(month.equals("09")){
         start = "'"+year+"-09-15'";
        end = "'"+year+"-09-31'";    
        }else if(month.equals("10")){
         start = "'"+year+"-10-15'";
        end = "'"+year+"-10-31'";    
        }else if(month.equals("11")){
        start = "'"+year+"-11-15'";
        end = "'"+year+"-11-30'";     
        }else if(month.equals("12")){
        start = "'"+year+"-12-15'";
        end = "'"+year+"-12-31'";     
        }
        System.out.print(em.size()+start+end);
        for(int i =0;i<em.size();i++){
           System.out.println(""+i);
            System.out.println(""+em.size());
        String check  = "INSERT INTO SALARY_PAYMENT VALUES('"+id()+"','"+em.get(i).getid()+"','"+year+"-"+month+"-"+day+"',"+start+","+end+",'N')";
        System.out.println(check);
        try{        
        /*con = DriverManager.getConnection("jdbc:mysql://localhost:3306/u787124245_dulce","root","");*/
        con = DriverManager.getConnection(d.url(),d.username(),d.password());
        pat = con.prepareStatement(check);
        pat.executeUpdate();
        pat.close();
        con.close();
        }catch(Exception e){
            System.out.println(e);
    }
}
}
}
    }//GEN-LAST:event_Employee_Payment_btnActionPerformed

    private void View_Employee_Payment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_Employee_Payment_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_View_Employee_Payment_btnActionPerformed

    private void Set_Period_Payment_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Set_Period_Payment_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Set_Period_Payment_btnActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void Employee_Clockin_out_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_Clockin_out_btnActionPerformed

    }//GEN-LAST:event_Employee_Clockin_out_btnActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        Product_Order_view p = new Product_Order_view();
        p.setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
    m.setreceive(1);
    Product_Order_view p = new Product_Order_view();
    p.setVisible(true);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void Employee_Payment_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_Payment_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Employee_Payment_btn1ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        Product_panel p = new Product_panel();
        p.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        Menu_panel m = new Menu_panel();
        m.setVisible(true);
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        Stock_panel s = new Stock_panel();
        s.setVisible(true);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JButton Change_schedule;
    private javax.swing.JButton CreateSchedule;
    private javax.swing.JPanel Employee;
    private javax.swing.JButton Employee_Clockin_out_btn;
    private javax.swing.JButton Employee_Management_btn;
    private javax.swing.JButton Employee_Payment_btn;
    private javax.swing.JButton Employee_Payment_btn1;
    private javax.swing.JButton Employee_btn;
    private javax.swing.JPanel Employee_panel;
    private javax.swing.JButton Employee_salary;
    private javax.swing.JButton Employee_salary_btn;
    private javax.swing.JPanel Firstpage;
    private javax.swing.JLabel Heading_INV;
    private javax.swing.JLabel Heading_INV1;
    private javax.swing.JLabel Heading_MO;
    private javax.swing.JLabel Heading_OP;
    private javax.swing.JLabel Heading_Sc;
    private javax.swing.JButton Inventory_btn;
    private javax.swing.JPanel Inventory_panel;
    private javax.swing.JButton Leave_list;
    private javax.swing.JButton Management_btn;
    private javax.swing.JPanel Management_panel;
    private javax.swing.JPanel Menu_Ordering;
    private javax.swing.JButton Menu_Ordering_btn;
    private javax.swing.JButton Ordering_product1;
    private javax.swing.JPanel Schedule;
    private javax.swing.JButton Schedule_btn;
    private javax.swing.JPanel Selection;
    private javax.swing.JButton Set_Period_Payment_btn;
    private javax.swing.JButton ShowSchedule;
    private javax.swing.JLabel Showdate;
    private javax.swing.JLabel Showtime;
    private javax.swing.JLabel Time1;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton View_Employee_Payment_btn;
    private javax.swing.JButton editenrolled;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton leave;
    private javax.swing.JLabel name;
    private javax.swing.JButton ordering_management;
    private javax.swing.JButton preenrolled;
    private javax.swing.JButton product_panel;
    private javax.swing.JLabel showname;
    private javax.swing.JButton view_leave;
    // End of variables declaration//GEN-END:variables
}
