
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yonshisoru
 */
public class Product_Units_Type_Panel extends javax.swing.JFrame {
ArrayList<Product_variable> Product_Unit_Array = new ArrayList<>();
//----------------------------------------------  
    Database d = new Database();
    Employee e = new Employee();
    Main_variable m = new Main_variable();
//---------------------------------------------- 
    Connection con = null;
    Statement st = null;
    PreparedStatement pat = null;
    ResultSet rs = null;
//---------------------------------------------- 
    public String id = null;
    String output = null;
    String menu = null;
    String password= null;
    String createid = null;
//----------------------------------------------  
    boolean editnaja = false;
    boolean createnaja = true;
    boolean deletenaja = false;
    boolean pass = false;
//---------------------------------------------- 
    int max = 0;
    /**
     * Creates new form Product_Units_Type_Panel
     */
    public Product_Units_Type_Panel() {
        initComponents();
        getProduct_Unit_Array();
        showProduct_Unit_Array();
        id();
    }
public void clear(){
         m_name_txt.setText("");
    }
    public void lock(){
         m_name_txt.setEnabled(false);
    }
    public void unlock(){
         m_name_txt.setEnabled(true);
    }
 public Connection getcon(){
     try{
     Class.forName("com.mysql.jdbc.Driver");
    con = DriverManager.getConnection(d.url(),d.username(),d.password());  
     }catch(Exception e){
         System.out.println(e);
     }
     return con;
 }
  public String id(){
       int count=0;
          String sql  ="select PRO_UNITS_TYPE from PRODUCT_UNIT_LIST";
    try{
    pat = getcon().prepareStatement(sql);
    rs = pat.executeQuery(sql);
    while(rs.next()){
        count++;
        if(Integer.parseInt(rs.getString("PRO_UNITS_TYPE"))>max){
            max = Integer.parseInt(rs.getString("PRO_UNITS_TYPE"));
        }
    }
    if(count==0){
            max = 0;
    }
    max += 1;
    if(max<10){
        output = "00"+max;
    }else if(max<100){
        output = "0"+max;
    }
    showid_txt.setText(output);
    createid = output;
    rs.close();
    pat.close();
    getcon().close();
            }catch(Exception e){
                e.printStackTrace();
            }
    return output;
   }
   public void getProduct_Unit_Array(){
        try{
        String sql  ="select PRO_UNITS_TYPE,PRO_UNITS_TYPE_NAME FROM PRODUCT_UNIT_LIST WHERE PRO_UNITS_TYPE_DEL = 'N' ORDER BY PRO_UNITS_TYPE";         
        /*con = DriverManager.getConnection("jdbc:mysql://localhost:3306/u787124245_dulce","root","");*/
        pat = getcon().prepareStatement(sql);
        rs = pat.executeQuery(sql);
        while(rs.next()){
           Product_variable p = new Product_variable();
            p.setunits_type(rs.getString("PRO_UNITS_TYPE"));
            p.setunits_type_name(rs.getString("PRO_UNITS_TYPE_NAME"));
            Product_Unit_Array.add(p);
        }
        rs.close();
        pat.close();
        getcon().close();
        }catch(Exception e){
            System.out.print(e);
        }
}
    public void showProduct_Unit_Array(){
        ArrayList<Product_variable>MenuTypeList = Product_Unit_Array;
        DefaultTableModel model = (DefaultTableModel)Product_Unit_Table.getModel();
        Object[] row = new Object[2];
        for(int i=0;i<MenuTypeList.size();i++){
            row[0]=MenuTypeList.get(i).getunit_type();
            row[1]=MenuTypeList.get(i).getunit_type_name();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Product_Unit_Table = new javax.swing.JTable();
        showid_txt = new javax.swing.JTextField();
        m_name_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        delete = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        create = new javax.swing.JRadioButton();
        edit = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Product_Unit_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รหัสหน่วย", "ชื่อหน่วย"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Product_Unit_Table.getTableHeader().setReorderingAllowed(false);
        Product_Unit_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Product_Unit_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Product_Unit_Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 360, 380));

        showid_txt.setEditable(false);
        showid_txt.setEnabled(false);
        getContentPane().add(showid_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 110, 30));
        getContentPane().add(m_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 190, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("รหัสหน่วย:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ชื่อหน่วย:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jButton1.setText("ปิด");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 80, 30));

        jButton2.setText("ยืนยัน");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, 30));

        jButton3.setText("เคลียร์");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 80, 30));

        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("ฟังก์ชั่น:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        create.setSelected(true);
        create.setEnabled(false);
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        getContentPane().add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        edit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                editFocusLost(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabel13.setText("ลบ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel14.setText("สร้าง");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel15.setText("แก้ไข");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Product_Unit_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Product_Unit_TableMouseClicked
        if(editnaja==true||deletenaja==true){
            showid_txt.setText(Product_Unit_Table.getModel().getValueAt(Product_Unit_Table.getSelectedRow(),0).toString());
            m_name_txt.setText(Product_Unit_Table.getModel().getValueAt(Product_Unit_Table.getSelectedRow(),1).toString());
        }
    }//GEN-LAST:event_Product_Unit_TableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Product_Unit_ID = showid_txt.getText();
        String Product_Unit_Name = m_name_txt.getText();
        if(createnaja==true){
            if(Product_Unit_Name.isEmpty()){
                JOptionPane.showMessageDialog(null,"KAPPA");
            }else{
                String eiei = "INSERT INTO PRODUCT_UNIT_LIST VALUE('"+Product_Unit_ID+"','"+Product_Unit_Name+"','N')";
                System.out.print(eiei);
                try{
                    pat = getcon().prepareStatement(eiei);
                    pat.executeUpdate(eiei);
                    pat.close();
                    getcon().close();
                }catch(Exception e){
                    System.out.print(e);
                }
                DefaultTableModel dm = (DefaultTableModel)Product_Unit_Table.getModel();
                while(dm.getRowCount() > 0)
                {
                    dm.removeRow(0);
                }
                Product_Unit_Array.clear();
                getProduct_Unit_Array();
                showProduct_Unit_Array();
                id();
                clear();
                    JOptionPane.showMessageDialog(null,"ทำรายการเสร็จสิ้น");
            }
        }else if(editnaja==true){
            if(Product_Unit_Name.isEmpty()){
                JOptionPane.showMessageDialog(null,"KAPPA");
            }else{
            String edit = "UPDATE PRODUCT_UNIT_LIST SET PRO_UNITS_TYPE_NAME = '"+Product_Unit_Name+"' WHERE PRO_UNITS_TYPE = '"+Product_Unit_ID+"'";
            System.out.print(edit);
            try{
                pat = getcon().prepareStatement(edit);
                pat.executeUpdate(edit);
                pat.close();
                clear();
                getcon().close();
            }catch(Exception e){
                System.out.print(e);
            }
            DefaultTableModel dm = (DefaultTableModel)Product_Unit_Table.getModel();
            System.out.print(dm.getRowCount());
            while(dm.getRowCount() > 0)
            {
                dm.removeRow(0);
            }
                Product_Unit_Array.clear();
                getProduct_Unit_Array();
                showProduct_Unit_Array();
                clear();
                JOptionPane.showMessageDialog(null,"ทำรายการเสร็จสิ้น");
            }
        }else if(deletenaja==true){
            String delete = "UPDATE PRODUCT_UNIT_LIST SET PRO_UNITS_TYPE_DEL = 'Y' WHERE PRO_UNITS_TYPE ='"+Product_Unit_ID+"'";
            System.out.print(delete);
            try{
                pat = getcon().prepareStatement(delete);
                pat.executeUpdate(delete);
                pat.close();
                clear();
                getcon().close();
            }catch(Exception e){
                System.out.print(e);
            }
            DefaultTableModel dm = (DefaultTableModel)Product_Unit_Table.getModel();
            System.out.print(dm.getRowCount());
            while(dm.getRowCount() > 0)
            {
                dm.removeRow(0);
            }
                Product_Unit_Array.clear();
                getProduct_Unit_Array();
                showProduct_Unit_Array();
                clear();
                showid_txt.setText("NAN");
                JOptionPane.showMessageDialog(null,"ทำรายการเสร็จสิ้น");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clear();
        showid_txt.setText(createid);
        Product_Unit_Table.getSelectionModel().clearSelection();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        lock();
        clear();
        showid_txt.setText("NAN");
        Product_Unit_Table.getSelectionModel().clearSelection();
        System.out.print("delete!!");
        delete.setEnabled(false);
        create.setEnabled(true);
        edit.setEnabled(true);
        create.setSelected(false);
        edit.setSelected(false);
        deletenaja = true;
        editnaja = false;
        createnaja = false;
    }//GEN-LAST:event_deleteActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        unlock();
        clear();
        Product_Unit_Table.getSelectionModel().clearSelection();
        System.out.print("create!!");
        create.setEnabled(false);
        edit.setEnabled(true);
        delete.setEnabled(true);
        showid_txt.setText(createid);
        delete.setSelected(false);
        edit.setSelected(false);
        createnaja = true;
        editnaja = false;
        deletenaja = false;
    }//GEN-LAST:event_createActionPerformed

    private void editFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_editFocusLost

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        unlock();
        clear();
        showid_txt.setText("NAN");
        Product_Unit_Table.getSelectionModel().clearSelection();
        System.out.print("edit!!");
        edit.setEnabled(false);
        create.setEnabled(true);
        delete.setEnabled(true);
        delete.setSelected(false);
        create.setSelected(false);
        editnaja=true;
        createnaja = false;
        deletenaja = false;
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product_Units_Type_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product_Units_Type_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product_Units_Type_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product_Units_Type_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product_Units_Type_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Product_Unit_Table;
    private javax.swing.JRadioButton create;
    private javax.swing.JRadioButton delete;
    private javax.swing.JRadioButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField m_name_txt;
    private javax.swing.JTextField showid_txt;
    // End of variables declaration//GEN-END:variables
}
