/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yonshisoru
 */
public class Schedule_leave extends javax.swing.JFrame {
   Database d = new Database();
    Connection con = null;
    PreparedStatement pat = null;
    ResultSet rs = null;
    Statement st = null;
    int period = 0;
    String status =null; 
    /**
     * Creates new form Schedule_leave
     */
    public Schedule_leave() {
        initComponents();
        showSchedule();
    }
  public ArrayList<Schedule>ScheduleList(){
        Employee ep = new Employee();
        ArrayList<Schedule> Schedulelist = new ArrayList<>();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        String sql  ="select SC_ID,SC_DATE,SCS_ID,SCS_NAME,SC_EMPLIMIT,SC_EMPCUR,SC_LEAVE,SC_DEL,SL_NUMBER,SL_STATUS FROM (SCHEDULE NATURAL JOIN SC_SHIFT)NATURAL JOIN SCHEDULE_LIST WHERE SC_DEL = 'N' AND EMP_ID ='"+ep.getshowid()+"' ORDER BY SL_NUMBER;";         
        /*con = DriverManager.getConnection("jdbc:mysql://localhost:3306/u787124245_dulce","root","");*/
        con = DriverManager.getConnection(d.url(),d.username(),d.password());
        pat = con.prepareStatement(sql);
        rs = pat.executeQuery(sql);
        while(rs.next()){
            Schedule e = new Schedule(rs.getString("SC_ID"),rs.getString("SC_DATE"),rs.getString("SCS_NAME"),rs.getInt("SC_EMPLIMIT"),rs.getInt("SC_EMPCUR"),rs.getInt("SC_LEAVE"));
            if(rs.getString("SL_STATUS").equals("N")){
                 e.setstatus("อยู่ในเวลางาน");
            }else if(rs.getString("SL_STATUS").equals("Y")){
            e.setstatus("ลงเวลาออกเรียบร้อยแล้ว");
            }else if(rs.getString("SL_STATUS").equals("O")){
            e.setstatus("ลา/วันหยุด");  
            }
            e.setlistid(rs.getInt("SL_NUMBER"));
            Schedulelist.add(e);
        }
        con.close();
        pat.close();
        rs.close();
        }catch(Exception e){
            e.printStackTrace();
        }
        return Schedulelist;
    }
       private void showSchedule(){
        ArrayList<Schedule> Schedule = ScheduleList();
        DefaultTableModel model = (DefaultTableModel)ShowSchedule.getModel();
        Object[] row = new Object[4];
        for(int i=0;i<Schedule.size();i++){
            row[0]=Schedule.get(i).getlistid();
            row[1]=Schedule.get(i).getdate();
            row[2]=Schedule.get(i).getperiod();
            row[3]=Schedule.get(i).getstatus();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ShowSchedule = new javax.swing.JTable();
        Confirm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        date_txt = new javax.swing.JTextField();
        period_txt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        cause = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(927, 651));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ShowSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รหัสการลงเวลางาน", "วันที่", "กะเวลา", "สถานะ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ShowSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowScheduleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ShowSchedule);
        if (ShowSchedule.getColumnModel().getColumnCount() > 0) {
            ShowSchedule.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 560, 400));

        Confirm.setText("ยืนยัน");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(Confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 537, 117, 48));

        jButton2.setText("ปิด");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 537, 122, 48));

        date_txt.setEditable(false);
        getContentPane().add(date_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 141, 33));

        period_txt.setEditable(false);
        getContentPane().add(period_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 141, 33));

        cause.setColumns(20);
        cause.setRows(5);
        jScrollPane2.setViewportView(cause);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 257, 190));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("วันที่:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("กะเวลา:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("สาเหตุการลา");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("แบบฟอร์มการลา");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ID.setText("รหัสการลงเวลางาน:");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        id_txt.setEditable(false);
        getContentPane().add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 141, 33));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowScheduleMouseClicked
        id_txt.setText(ShowSchedule.getModel().getValueAt(ShowSchedule.getSelectedRow(),0).toString());
        date_txt.setText(ShowSchedule.getModel().getValueAt(ShowSchedule.getSelectedRow(),1).toString());
        if(ShowSchedule.getModel().getValueAt(ShowSchedule.getSelectedRow(),2).toString().equals("08.00-15.30")){
            period = 1;
        }else if(ShowSchedule.getModel().getValueAt(ShowSchedule.getSelectedRow(),2).toString().equals("15.00-22.30")){
            period = 2;
        }
        period_txt.setText(ShowSchedule.getModel().getValueAt(ShowSchedule.getSelectedRow(),2).toString());
        System.out.print(period);
        status = ShowSchedule.getModel().getValueAt(ShowSchedule.getSelectedRow(),3).toString();
    }//GEN-LAST:event_ShowScheduleMouseClicked

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
     if(status.equals("ลา/วันหยุด") || (status.equals("ลงเวลาออกเรียบร้อยแล้ว"))){
         JOptionPane.showMessageDialog(null, "ยกเลิกรายการ เนื่องจากตารางเวลานี้มีการลาหรือลงเวลาออกเรียบร้อยแล้ว","System",ERROR_MESSAGE);
     }else{
     String sql  ="UPDATE SCHEDULE_LIST SET SL_STATUS = 'O',SL_CAUSE = '"+cause.getText()+"' WHERE SL_NUMBER = '"+id_txt.getText()+"'";
     String select = "SELECT SC_ID,SC_EMPLIMIT,SC_EMPCUR,SC_LEAVE FROM SCHEDULE WHERE SC_DATE = '"+date_txt.getText()+"' AND SCS_ID = '"+period+"' AND SC_DEL = 'N'";
     int limit = 0;
     int cur = 0;
     int leave = 0;
     String id =null;
     try{
        Class.forName("com.mysql.jdbc.Driver");
        /*con = DriverManager.getConnection("jdbc:mysql://localhost:3306/u787124245_dulce","root","");*/
        con = DriverManager.getConnection(d.url(),d.username(),d.password());
        pat = con.prepareStatement(select);
        rs = pat.executeQuery(select);
        while(rs.next()){
            limit = rs.getInt("SC_EMPLIMIT");
            cur = rs.getInt("SC_EMPCUR");
            id = rs.getString("SC_ID");
            leave = rs.getInt("SC_LEAVE");
            System.out.print(id+""+cur);
        }
        rs.close();
        pat.close();
        con.close();
        }catch(Exception e){ 
     }
     try{
        Class.forName("com.mysql.jdbc.Driver");
        /*con = DriverManager.getConnection("jdbc:mysql://localhost:3306/u787124245_dulce","root","");*/
        con = DriverManager.getConnection(d.url(),d.username(),d.password());
        pat = con.prepareStatement(sql);
        pat.executeUpdate(sql);
        pat.close();
        con.close();
        }catch(Exception e){
            
        }
    String schedule  ="UPDATE SCHEDULE SET SC_EMPCUR = '"+(cur-1)+"' , SC_LEAVE = '"+(leave+1)+"' WHERE SC_ID = '"+id+"'"; 
     try{
        Class.forName("com.mysql.jdbc.Driver");
        /*con = DriverManager.getConnection("jdbc:mysql://localhost:3306/u787124245_dulce","root","");*/
        con = DriverManager.getConnection(d.url(),d.username(),d.password());
        pat = con.prepareStatement(schedule);
        pat.executeUpdate(schedule);
        JOptionPane.showMessageDialog(null, "บันทึกสำเร็จ");
        pat.close();
        con.close();
        }catch(Exception e){
            
        }
        DefaultTableModel dk = (DefaultTableModel)ShowSchedule.getModel();
        while(dk.getRowCount() > 0)
        {       
        dk.removeRow(0);
        }
             showSchedule();
     }    
    }//GEN-LAST:event_ConfirmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Schedule_leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Schedule_leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Schedule_leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Schedule_leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Schedule_leave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirm;
    private javax.swing.JLabel ID;
    private javax.swing.JTable ShowSchedule;
    private javax.swing.JTextArea cause;
    private javax.swing.JTextField date_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField period_txt;
    // End of variables declaration//GEN-END:variables
}
