/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yonshisoru
 */
public class Schedule_show_emp_leave extends javax.swing.JFrame {
    Main_variable m = new Main_variable();
    Employee em = new Employee();
    Database d = new Database();
    Connection con = null;
    PreparedStatement pat = null;
    ResultSet rs = null;
    Statement st = null;
    /**
     * Creates new form Schedule_Employee
     */
    public Schedule_show_emp_leave() {
        initComponents();
        showid.setText(em.getshowid());
        showname.setText(em.getdisfname()+" "+em.getdislname());   
        showSchedule();
    }
  public ArrayList<Schedule>ScheduleList(){
        ArrayList<Schedule> Schedulelist = new ArrayList<>();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        String sql  ="SELECT SL_NUMBER,EMP_ID,SCS_ID,SC_DATE,SL_STATUS,SCS_NAME,SL_CAUSE FROM (SCHEDULE NATURAL JOIN SC_SHIFT)NATURAL JOIN SCHEDULE_LIST WHERE EMP_ID = '"+em.getshowid()+"' AND SL_STATUS = 'O';";         
        /*con = DriverManager.getConnection("jdbc:mysql://localhost:3306/u787124245_dulce","root","");*/
        con = DriverManager.getConnection(d.url(),d.username(),d.password());
        pat = con.prepareStatement(sql);
        rs = pat.executeQuery(sql);
        while(rs.next()){
            Schedule e = new Schedule();
            e.setlistid(rs.getInt("SL_NUMBER"));
            e.setDate(rs.getString("SC_DATE"));
            e.setperiodid(rs.getInt("SCS_ID"));
            if(rs.getInt("SCS_ID")==1){
                e.setperiod("08.00-15.30");
            }else{
                e.setperiod("15.00-22.30");
            }
            e.setcause(rs.getString("SL_CAUSE"));
            Schedulelist.add(e);
        }
        con.close();
        pat.close();
        rs.close();
        }catch(Exception e){
            e.printStackTrace();
        }
        return Schedulelist;
    }
       private void showSchedule(){
        ArrayList<Schedule> Schedule = ScheduleList();
        DefaultTableModel model = (DefaultTableModel)ShowSchedule.getModel();
        Object[] row = new Object[4];
        for(int i=0;i<Schedule.size();i++){
            row[0]=Schedule.get(i).getlistid();
            row[1]=Schedule.get(i).getdate();
            row[2]=Schedule.get(i).getperiod();
            row[3]=Schedule.get(i).getcause();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ShowSchedule = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        showid = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();
        showname = new javax.swing.JLabel();
        id2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(694, 501));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ShowSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "รหัสการลา", "วันที่", "กะเวลา", "สาเหตุ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ShowSchedule);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 650, 270));

        jButton1.setText("ปิด");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 170, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("ตารางการลา");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        showid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(showid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 90, 20));

        id1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id1.setText("รหัสพนักงาน:");
        getContentPane().add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        showname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(showname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 270, 20));

        id2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id2.setText("ชื่อพนักงาน:");
        getContentPane().add(id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         m.seton(0);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
         m.seton(0);
    }//GEN-LAST:event_formWindowDeactivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Schedule_show_emp_leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Schedule_show_emp_leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Schedule_show_emp_leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Schedule_show_emp_leave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Schedule_show_emp_leave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ShowSchedule;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel id2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel showid;
    private javax.swing.JLabel showname;
    // End of variables declaration//GEN-END:variables
}
