
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yonshisoru
 */
public class Waste_View extends javax.swing.JFrame {
ArrayList<Stock_Variable>Waste_List_Array = new ArrayList<>();
//-----------------------------------------
    Database d = new Database();
    Employee e = new Employee();
    Main_variable m = new Main_variable();
    Waste_variable w = new Waste_variable();
//------------------------------------------
    Connection con = null;
    Statement st = null;
    PreparedStatement pat = null;
    ResultSet rs = null;
    
    /**
     * Creates new form Waste_View
     */
    public Waste_View() {
        initComponents();
        waste_txt.setText(w.getglobalid());
        getWaste_List();
        showWaste_List();
    }
        public Connection getcon(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            return DriverManager.getConnection(d.url(),d.username(),d.password());
        }catch(Exception e){
            System.out.println(e.getMessage());
            System.out.println("Didn';t connect");
            throw new RuntimeException(e);
        }
    }
   public void getWaste_List(){
        try{
        String sql  ="select WL_NUMBER,WL_UNIT,WL_CAUSE,WL_PRICE,PRO_ID,PRO_NAME,PRO_PRICE FROM WASTE_LIST NATURAL JOIN PRODUCT WHERE WL_DEL = 'N' AND W_ID = '"+w.getglobalid()+"'";
        System.out.println(sql);
        /*con = DriverManager.getConnection("jdbc:mysql://localhost:3306/u787124245_dulce","root","");*/
        st = getcon().createStatement();
        rs = st.executeQuery(sql);
        while(rs.next()){
            Stock_Variable s = new Stock_Variable();
            s.setstocknumber(rs.getInt("WL_NUMBER"));
            s.setstockunits(rs.getDouble("WL_UNIT"));
            s.setproductid(rs.getString("PRO_ID"));
            s.setproductname(rs.getString("PRO_NAME"));
            s.p.setprice(rs.getInt("PRO_PRICE"));
            s.setdetail(rs.getString("WL_CAUSE"));
            s.setstockprice(rs.getDouble("WL_PRICE"));
            Waste_List_Array.add(s);
        }
        rs.close();
        st.close();
        getcon().close();
        }catch(Exception e){
            System.out.print(e);
        }
} 
       public void showWaste_List(){
        DefaultTableModel model = (DefaultTableModel)waste_stock_table.getModel();
        Object[] row = new Object[5];
        for(int i=0;i<Waste_List_Array.size();i++){
            row[0]=Waste_List_Array.get(i).getproductname();
            row[1]=Waste_List_Array.get(i).p.getprice();
            row[2]=Waste_List_Array.get(i).getstockunits();
            row[3]=Waste_List_Array.get(i).p.getprice()*Waste_List_Array.get(i).getstockunits();
            row[4]=Waste_List_Array.get(i).getdetail();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        waste_stock_table = new javax.swing.JTable();
        waste_txt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(890, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        waste_stock_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ชื่อสินค้า", "ราคาต่อหน่วย", "จำนวนที่ทิ้ง", "มูลค่าทั้งหมด", "สาเหตุการทิ้ง"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        waste_stock_table.getTableHeader().setReorderingAllowed(false);
        waste_stock_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                waste_stock_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(waste_stock_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 700, 450));

        waste_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        waste_txt.setText("WasteID:");
        getContentPane().add(waste_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("WasteID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jButton1.setText("ปิด");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 110, 40));

        jButton2.setText("ลบ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void waste_stock_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_waste_stock_tableMouseClicked

    }//GEN-LAST:event_waste_stock_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(JOptionPane.showConfirmDialog(null,"คุณต้องการที่จะลบรายการทิ้งที่ "+w.getglobalid()+" จริงหรือไม่",null,YES_NO_OPTION)==YES_OPTION){
            String deletewaste = "UPDATE WASTE SET W_DEL = 'Y' WHERE W_ID = '"+w.getglobalid()+"'";
            String deletewastelist = "UPDATE WASTE_LIST SET WL_DEL = 'Y' WHERE W_ID = '"+w.getglobalid()+"'";
            try{
                pat = getcon().prepareStatement(deletewaste);
                pat.executeUpdate(deletewaste);
                pat.close();
                    pat = getcon().prepareStatement(deletewastelist);
                    pat.executeUpdate(deletewastelist);
                    pat.close();
                getcon().close();
                JOptionPane.showMessageDialog(null,"ทำรายการเสร็จสิ้น");
                this.setVisible(false);
                Waste w = new Waste();
                w.setVisible(true);
            }catch(Exception e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Waste_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Waste_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Waste_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Waste_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Waste_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable waste_stock_table;
    private javax.swing.JLabel waste_txt;
    // End of variables declaration//GEN-END:variables
}
