/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dulce.simply;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yonshisoru
 */
public class Salary_payment extends javax.swing.JFrame {
   Database d = new Database();
    Connection con = null;
    PreparedStatement pat = null;
    ResultSet rs = null;
    Statement st = null;
    String year = null;
    String month = null;
    String day = null;
    /**
     * Creates new form Payment
     */
    public Salary_payment() {
        initComponents();
        showSchedule();
        //test();
    }
   public ArrayList<Salary_variable>Salary_payment_List(){
        String change = "SELECT SP_ID,EMP_ID,EMP_FNAME,EMP_LNAME,EMP_SALARY,SP_DATE,SP_S_PEROID,SP_E_PEROID,SUM(W_TOTALTIME),(EMP_SALARY*W_TOTALTIME) FROM (SALARY_PAYMENT NATURAL JOIN EMPLOYEE)NATURAL JOIN WORKTIME WHERE W_STATUS = 'Y' AND EMP_DEL = 'N' AND W_DATE BETWEEN SP_S_PEROID AND SP_E_PEROID GROUP BY EMP_ID HAVING SUM(W_TOTALTIME) ORDER BY SP_ID";         
        System.out.print(change);
        ArrayList<Salary_variable> Salary_payment = new ArrayList<>();
        try{
        Class.forName("com.mysql.jdbc.Driver");     
        /*con = DriverManager.getConnection("jdbc:mysql://localhost:3306/u787124245_dulce","root","");*/
        con = DriverManager.getConnection(d.url(),d.username(),d.password());
        pat = con.prepareStatement(change);
        rs = pat.executeQuery(change);
        while(rs.next()){
            Salary_variable ep = new Salary_variable(rs.getString("SP_ID"),rs.getString("EMP_FNAME"),rs.getString("EMP_LNAME"),rs.getString("SP_DATE"),rs.getInt("EMP_SALARY"),rs.getString("SP_S_PEROID"),rs.getString("SP_E_PEROID"),rs.getDouble("SUM(W_TOTALTIME)"),rs.getInt("EMP_SALARY")*rs.getDouble("SUM(W_TOTALTIME)"));
            Salary_payment.add(ep);
        }
        rs.close();
        pat.close();
        con.close();
        }catch(Exception e){
            e.printStackTrace();
        }
        return Salary_payment;
    }
   /*public void test(){
        ArrayList<Salary_variable> Schedule = ScheduleList();
        System.out.print(Schedule.size());
        for(int i =0;i<Schedule.size();i++){
            System.out.print(Schedule.get(i).getid());
        }
   }*/
       private void showSchedule(){
        ArrayList<Salary_variable> Salary_payment = Salary_payment_List();
        DefaultTableModel model = (DefaultTableModel)Show_salarypayment.getModel();
        Object[] row = new Object[8];
        for(int i=0;i<Salary_payment.size();i++){
            row[0]=Salary_payment.get(i).getid();
            row[1]=Salary_payment.get(i).getfname()+" "+Salary_payment.get(i).getlname();
            row[2]=Salary_payment.get(i).getdate();
            row[3]=Salary_payment.get(i).getstart();
            row[4]=Salary_payment.get(i).getend();
            row[5]=Salary_payment.get(i).getsalary();
            row[6]=Salary_payment.get(i).getworktime();
            row[7]=Salary_payment.get(i).getsum();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Show_payment = new javax.swing.JScrollPane();
        Show_salarypayment = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(930, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Show_salarypayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Date", "Started Period", "Ended Period", "Salary", "Worktime", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Show_payment.setViewportView(Show_salarypayment);

        getContentPane().add(Show_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 780, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salary_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salary_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salary_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salary_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salary_payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Show_payment;
    private javax.swing.JTable Show_salarypayment;
    // End of variables declaration//GEN-END:variables
}
